# Generated by Django 5.2 on 2025-04-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="Assign product to a specific store",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="posApp.store",
            ),
        ),
    ]
