# Generated by Django 5.2 on 2025-04-05 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posApp", "0002_products_store"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="code",
        ),
        migrations.RemoveField(
            model_name="products",
            name="description",
        ),
    ]
