# Generated by Django 5.2 on 2025-04-05 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posApp", "0003_remove_products_code_remove_products_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="Store where the sale occurred",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="posApp.store",
            ),
        ),
    ]
